### PR TITLE
Allow user to specify a path to the sonar-scanner project config to use

### PR DESCRIPTION
**Pull request by t1bb4r**
Reopen of #5 which hasn't had any changes for months. I'd really like to use this feature so I'm jumping ahead and making the changes myself.

### CODE REVIEW

**Review by amaanrizvi-cazoo — APPROVED** [review]
Looks good 👍

**Comment by t1bb4r** [comment]
@tom-vanbraband-sonarsource are you happy with these changes?

**Comment by t1bb4r** [comment]
I think circleci is failing either because the context isn't set up correctly for PR from a fork or maybe this issue https://github.com/CircleCI-Public/circleci-cli/issues/486. Let me know if I can do something to help @tom-vanbraband-sonarsource

**Comment by tom-vanbraband-sonarsource** [comment]
Apologies for the long delay. Created an internal copy for this PR (#11) to run the full CI pipeline, [I also contacted CircleCI](https://discuss.circleci.com/t/unable-to-publish-dev-version-of-orb/39124) for help with the failing CI job.

**Comment by exoego** [comment]
I am trying to use SonarCloud on monorepo with CircleCI.

IIUC, each projects in monorepo have different `sonar.projectKey`, so each projects should have different `sonar-project.properties`.

It seems that [GitHub Actions for SonarCloud](https://github.com/SonarSource/sonarcloud-github-action) can have diffrent `sonar.projectKey` via `arg` option.
However, the latest SonarCloud orb v1.0.2 does not support multiple properties files or `arg` option.

It seems that this PR brings that missing capability. (Isn't it ?)
Hope this get merged and new orb published soon 🙏

**Comment by tom-vanbraband-sonarsource** [comment]
Is resolved by #15

**Pull request closed without merging**
