### PR TITLE
Change version of Sonar Scanner. Update README

### PR DESCRIPTION
**Pull request by tom-vanbraband-sonarsource**

### CODE REVIEW

**Comment by vdhpieter** [comment]
@tom-vanbraband-sonarsource @marcin-majewski-sonarsource can we get this PR updated to the latest version and merged ASAP? It's a bit shameful that the official orb (that is marked as a partner orb by CircleCI). is running on a version that is at least 1,5 year old...

**Comment by MichaelDeBoey** [comment]
@tom-vanbraband-sonarsource Publishing seems to have failed
https://app.circleci.com/pipelines/github/SonarSource/sonarcloud-circleci-orb/54/workflows/45440892-e262-481b-ae3a-2cfc309d8a19

**Comment by tom-vanbraband-sonarsource** [comment]
@MichaelDeBoey Yes, publishing has failed because of a configuration issue. We will resolve this soon and re-pusblish the release

**Comment by vdhpieter** [comment]
@tom-vanbraband-sonarsource @marcin-majewski-sonarsource any update on this?

**Pull request merged**
